### ISSUE TITLE
Bug testing

### ISSUE THREAD

**Issue by AleksBekker** [beckandbekker/CalendarExtension#10]
I'm just gonna list the people who I know are bugtesting here.

Carlos Ruiz - 10
Harold Wang - 10 Basis Chandler I think
Rahul Vedanthum - 10
Shivam Kedia - 10

Maybe bugtesting:

Isabella Doty - 10
Naija Bruckner - 10

**Comment by howard-beck** [comment]
Don't need to test bugs if you write the code correctly in the first place!

**Comment by AleksBekker** [comment]
this is a safety net for you :)

**Comment by howard-beck** [comment]
:(

**Comment by NenjaSkillz** [comment]
>:)

**Comment by AleksBekker** [comment]
\>:)

**Comment by AleksBekker** [comment]
Update: Naija Bruckner has confirmed that she will bugtest.
